language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install -g cordova ionic
script:
 - cd Crolist/
 - cordova plugin rm cordova-plugin-console
 - cordova platform add android
 - cordova build --release android

deploy:
  skip_cleanup: true
