language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install -g cordova ionic
script:
 - chmod -x build_apk.sh
 - ./build_apk.sh

deploy:
  skip_cleanup: true
