language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
before install:
  - chmod -x build_apk.sh
install:
  -  cd Crolist/
  - echo "Install directory" && echo pwd
  - npm install
  - npm install -g cordova ionic
script:

 - ./build_apk.sh

deploy:
  skip_cleanup: true
